### ISSUE TITLE
Query cache on system table

### ISSUE THREAD

**Issue by gregzuro** [duyet/clickhouse-monitoring#400]
I just installed this on a virgin clickhouse server.

I set up the monitoring user as described in the [readme](https://github.com/duyet/clickhouse-monitoring/commit/33f5b33783fb346b48d26d7fd83fd2250138ce6c).

I get:
```
⨯ Error: The query result was not cached because the query contains a system table. Use setting `query_cache_system_table_handling = 'save'` or `= 'ignore'` to cache the query result regardless or to omit caching. 
    at t.parseError (/app/.next/server/chunks/9917.js:1:8197)
    at ClientRequest.f (/app/.next/server/chunks/9917.js:1:25146) {
  code: '719',
  type: 'QUERY_CACHE_USED_WITH_SYSTEM_TABLE',
  digest: '4153755405'
}
```

from this, and:

```
2024.11.08 15:38:55.170157 [ 8419 ] {829d44de-e5f7-41c4-b41e-bf419d40e4e3} <Error> DynamicQueryHandler: Code: 719. DB::Exception: The query result was not cached because the query contains a system table. Use setting `query_cache_system_table_handling = 'save'` or `= 'ignore'` to cache the query result regardless or to omit caching. (QUERY_CACHE_USED_WITH_SYSTEM_TABLE), Stack trace (when copying this message, always include the lines below):
```

from clickhouse.

I am also getting:
```
[/api/clean] error Error: Error when getting last cleanup: Error: The query result was not cached because the query contains a non-deterministic function. Use setting `query_cache_nondeterministic_function_handling = 'save'` or `= 'ignore'` to cache the query result regardless or to omit caching. 
    at m (/app/.next/server/app/api/clean/route.js:6:232)
    at async g (/app/.next/server/app/api/clean/route.js:1:1639)
    at async w (/app/.next/server/app/api/clean/route.js:1:1427)
    at async tn.do (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:17739)
    at async tn.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:21288)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:1493:42)
    at async responseGenerator (/app/node_modules/next/dist/server/base-server.js:1834:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1876:28)
    at async NextNodeServer.renderPageComponent (/app/node_modules/next/dist/server/base-server.js:2290:24)
```

from this.

**Comment by duyet** [comment]
Thank you for letting me know. The document has been updated; please refer to https://duyet.github.io/clickhouse-monitoring/getting-started/clickhouse-requirements and let me know if there are any issues with your setup.

Basically,

```xml
# File: users.d/monitoring_profile.xml
<clickhouse>
  <profiles>
    <monitoring_profile>
      <allow_experimental_analyzer>1</allow_experimental_analyzer>
 
      <!-- Optional: query cache to avoid hit too much queries on database -->
      <use_query_cache>1</use_query_cache>
      <query_cache_max_entries>0</query_cache_max_entries>

      <!-- add these -->
      <query_cache_system_table_handling>save</query_cache_system_table_handling> 
      <query_cache_nondeterministic_function_handling>save</query_cache_nondeterministic_function_handling>
    </monitoring_profile>
  </profiles>
</clickhouse>
```

**Comment by gregzuro** [comment]
Perfect.  Thanks!
